OD-609 [Fix] Correctly show a pointer cursor on inline links
Fliplet/fliplet-widget-inline-link pull request #8
Opened 2021-10-12 12:04 UTC by skrupnyk

@romanyosyfiv @inna-bieshulia

OD-609 https://weboo.atlassian.net/browse/OD-609

Description
**Problem:** Text links do not have a default pointer cursor because the desired styles are not specified for which the pointer should change.
**Solution:** Added styles that change cursor to pointer when hovering over a text link.

Screenshots/screencasts
https://storyxpress.co/video/kunzpzvym9gmznpfu

Backward compatibility
This change is fully backward compatible.

Reviewers
@upplabs-alex-levchenko

2021-10-13 13:00 UTC, tonytlwu requested changes

2021-10-13 13:00 UTC, tonytlwu commented on css/build.css
> +.inline-link {
You don't need to add a new class to the link. The widget has a container that provides sufficient context. It also means developers can have an element with a custom `inline-link` class without being affected.

```suggestion
[data-widget-package="com.fliplet.inline-link"] > a {
```

2021-10-13 13:00 UTC, tonytlwu commented on package.json
> +  "description": "Documentation is available at https://developers.fliplet.com/API/components/form-builder.html",
Incorrect reference

2021-10-19 12:38 UTC, skrupnyk commented on css/build.css
> +.inline-link {
fixed

2021-10-20 10:20 UTC, tonytlwu approved these changes
@romanyosyfiv @inna-bieshulia This is ready for testing

Risk: Low
Affected: Inline link users in apps
Verify: Users can click on the inline links

Squash and merge: Use PR title

2021-10-20 10:21 UTC, tonytlwu commented
@upplabs-alex-levchenko Feedback for the team: the PR title was "Ensures hidden fields in forms are not displayed to users" which looks like it's for an entirely different PR.

2021-10-20 11:31 UTC, merged